contact_links:
  - name: Get help on our Discord server
    url: https://discord.gg/VdCAUtm
    about: If your issue seems like it could possibly be an easy fix due to configuration, please hop on our Discord.
blank_issues_enabled: false
