name: Feature request
description: Suggest an idea for this project
title: "[Feature Request] "
labels: ["Feature Request"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this feature request! Please fill out the following form to your best ability to help us understand your feature request and significantly improve the chance of getting added.
      For anything else than a feature request, use: [our Discord server](https://discord.gg/VdCAUtm) or the [the Wiki](https://github.com/MaxMaeder/DriveBackupV2/wiki).
- type: textarea
  attributes:
    label: What feature do you want to see added?
    description: A clear and concise description of your feature request.
  validations:
    required: true
- type: textarea
  attributes:
    label: Are there any alternatives?
    description: List any alternatives you might have tried