name: DriveBackupV2 CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'DriveBackup/**'
  pull_request:
    paths:
      - 'DriveBackup/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml -B package --file DriveBackup/pom.xml
      env:
        USER_NAME: ${{ secrets.CRED_SERVER_USERNAME }}
        ACCESS_TOKEN: ${{ secrets.CRED_SERVER_PASSWORD }}
    - uses: actions/upload-artifact@v4
      with:
        name: DriveBackupV2.jar
        path: DriveBackup/target/DriveBackupV2.jar
